### ISSUE TITLE
Hard-coded widget sizes problematic

### ISSUE THREAD

**Issue by mwild1** [lcpz/awesome-copycats#253] opened 2019-01-19 15:36 UTC
The rc.lua template and the themes (well, at least the multicolor one) have hard-coded pixel values for the size of the primary wibars and client titlebars.

This is a problem as screens may have different DPIs, leading to the widgets being too small on HiDPI screens for example.

I removed the hard-coded values and everything scales as expected.

**Comment by lcpz** [comment] 2019-01-23 11:00
The problem is, some themes have fixed values in order to match some design (see Holo).

Also, the majority of users have at most full hd screens, with which the hard-coded values are fine.

I will add comments explaining to remove them in order to scale in higher resolution screens.

**Comment by lcpz** [comment] 2019-04-05 16:37
Closed by #258

**Closed by lcpz** 2019-04-05 16:37 UTC
