### ISSUE TITLE
run into connection time out issue during clone

### ISSUE THREAD

**Issue by Kelvin945** [lcpz/awesome-copycats#268] opened 2019-07-26 08:03 UTC
I have following output during cloning.

> Cloning into 'awesome-copycats'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4746 (delta 0), reused 1 (delta 0), pack-reused 4743
Receiving objects: 100% (4746/4746), 59.55 MiB | 9.28 MiB/s, done.
Resolving deltas: 100% (2316/2316), done.
Checking connectivity... done.
Submodule 'freedesktop' (git://github.com/lcpz/awesome-freedesktop.git) registered for path 'freedesktop'
Submodule 'lain' (git://github.com/lcpz/lain.git) registered for path 'lain'
Cloning into 'freedesktop'...
fatal: unable to connect to github.com:
github.com[0: 13.237.44.5]: errno=Connection timed out
fatal: clone of 'git://github.com/lcpz/awesome-freedesktop.git' into submodule path 'freedesktop' failed

**Comment by lcpz** [comment] 2019-08-12 16:10
Probably a temporary issue of GitHub.

I can't reproduce anyway, but if you still have this problem, just let me know. Closing.

**Closed by lcpz** 2019-08-12 16:10 UTC

**Comment by Kelvin945** [comment] 2019-08-13 07:04
i can clone the repository, but when clone with recursive flag, the sub-module 'freedesktop' will run into time out. But I find different repository "awesome-ban" which also using freedesktop is able to clone recursively.

**Comment by lcpz** [comment] 2019-08-14 19:12
I tried on 3 different machines and OSs, and still I am not able to reproduce.

The Freedesktop submodule is defined [correctly](https://github.com/lcpz/awesome-copycats/blob/master/.gitmodules), so are you sure it is not a problem on your end?

**Comment by Kelvin945** [comment] 2019-08-15 07:01
Just double check on git ban submodule.  it use https instead of git. It is said that clone via git might be block via firewall (https://stackoverflow.com/questions/8750930/git-clone-hangs-forever-on-github). is it possible to change it into https? Thank you for your patient.
