### ISSUE TITLE
Memory leak/doesn't get cleared

### ISSUE THREAD

**Issue by ngoonee** [lcpz/awesome-copycats#204] opened 2017-10-03 22:14 UTC
This is (probably) an awesome issue rather than a theme issue, but it is much worse (memory usage growth is much faster) while using copycats than using the stock awesome rc.lua (or my own customization of it which used quite a few vicious widgets and graphs).

For reference, the awesomewm bug report - https://github.com/awesomeWM/awesome/issues/2050 - has an unmerged patch. I can't test it right now, but will soon.

awesome memory usage starts off at 40-60MB, and after an hour it's hit 205 MB (and continues to grow). Triggering garbage collection doesn't return the memory, but does seem to slow the rate of growth (not scientifically measured).

Wondering if there's something specific to my system/install, or whether other users also experience the same.

**Comment by lcpz** [comment] 2017-10-04 10:57
Only  Copland, Holo and Vertex themes use shapes, and just for widgets. Also, Vertex uses a custom shape for the taglist. These are all singleton elements, while the linked issue is for clients.

This is indeed a duplicate of https://github.com/awesomeWM/awesome/issues/2050, which should be solved by [this PR](https://github.com/awesomeWM/awesome/pull/2051).

Of course, shapes increase by some percentage the memory usage, so you might want to disable them if you don't have much RAM, or want to maximise responsiveness.

**Closed by lcpz** 2017-10-04 10:57 UTC
Labels: awesome-bug, duplicate

**Comment by ngoonee** [comment] 2017-10-05 01:46
I'm not very concerned with amount of RAM used normally, but unchecked growth seems to be a bug. Will wait for a merger of that PR to test again, but I did have (once) a situation where awesome's memory usage went to over a gigabyte (coupled with two browsers open for some web tests, that managed to get the whole WM killed through the kernel OOM. Will monitor that report.

**Comment by lcpz** [comment] 2017-10-05 09:17
@ngoonee Are you sure the testing browsers weren't the major culprits?

The PR is just 1 line, you can apply it yourself and try your test case again, both with default `rc` and one of my themes (or using shaped clients) to see if there are problems. I suggest to use [perf-tools](https://github.com/brendangregg/perf-tools) or [flamegraph](http://www.brendangregg.com/flamegraphs.html) to monitor possible leaks.

**Comment by ngoonee** [comment] 2017-10-06 01:14
Oh, they're definitely culprits as well, but I was surprised that top showed awesome as having a GB of usage.

Unfortunately I can't seem to replicate that behaviour now.... I get consistent memory growth for awesome but the rate of growth doesn't seem like it'll hit 1GB anytime soon.
